// GENERATED by scripts/sync-blog-guides.mjs from the blog repo - do not edit by hand.
// shop category slug -> matching guides on preisgucken.com (shown on category pages).
export const BLOG_GUIDES = {
  "gartengeraete": [
    {
      "title": "Gartengeräte kaufen: Akku, Kabel oder Benzin? Heckenschere, Trimmer & Bewässerung",
      "url": "https://www.preisgucken.com/blog/gartengeraete-kaufen-ratgeber/"
    }
  ],
  "schlafen": [
    {
      "title": "7 Fehler beim Boxspringbett-Kauf, die dich Geld kosten",
      "url": "https://www.preisgucken.com/blog/boxspringbett-kaufen-ratgeber/"
    },
    {
      "title": "Falscher Härtegrad, schlechter Schlaf: So triffst du die richtige Wahl",
      "url": "https://www.preisgucken.com/blog/matratze-kaufen-ratgeber/"
    }
  ],
  "sitzen": [
    {
      "title": "Welches Sofa passt zu deinem Wohnzimmer? Der Entscheidungs-Guide",
      "url": "https://www.preisgucken.com/blog/sofa-kaufen-ratgeber/"
    }
  ],
  "gartenmoebel": [
    {
      "title": "Polyrattan, Alu oder Holz? Der Gartenmöbel-Materialvergleich",
      "url": "https://www.preisgucken.com/blog/gartenmoebel-kaufen-ratgeber/"
    }
  ],
  "vorhaenge": [
    {
      "title": "Verdunkelung, Schallschutz oder Deko? Welcher Vorhang wofür taugt",
      "url": "https://www.preisgucken.com/blog/vorhaenge-kaufen-ratgeber/"
    }
  ],
  "leuchten": [
    {
      "title": "Hängelampe oder Stehlampe? So findest du die richtige Design-Leuchte",
      "url": "https://www.preisgucken.com/blog/haengelampe-oder-stehlampe-design-leuchte/"
    },
    {
      "title": "Wohnaccessoires und Beleuchtung im Preisvergleich: So wertest du dein Zuhause auf",
      "url": "https://www.preisgucken.com/blog/wohnaccessoires-beleuchtung-preisvergleich/"
    }
  ],
  "wohnaccessoires": [
    {
      "title": "Wohnaccessoires und Beleuchtung im Preisvergleich: So wertest du dein Zuhause auf",
      "url": "https://www.preisgucken.com/blog/wohnaccessoires-beleuchtung-preisvergleich/"
    }
  ],
  "grills-outdoor-kueche": [
    {
      "title": "Grill kaufen: Gas, Kohle oder Elektro? Der Grilltyp-Guide",
      "url": "https://www.preisgucken.com/blog/grill-kaufen-gas-kohle-elektro-guide/"
    }
  ],
  "maehroboter": [
    {
      "title": "Mähroboter ohne Begrenzungskabel kaufen: Der RTK-Guide",
      "url": "https://www.preisgucken.com/blog/maehroboter-kaufen-ohne-begrenzungskabel/"
    }
  ],
  "sessel": [
    {
      "title": "Gaming Stuhl kaufen: Material, Ergonomie & Massage-Funktion",
      "url": "https://www.preisgucken.com/blog/gaming-stuhl-kaufen-ratgeber/"
    }
  ],
  "schmuck": [
    {
      "title": "Echt oder Fake? So erkennst du hochwertigen Schmuck in 60 Sekunden",
      "url": "https://www.preisgucken.com/blog/schmuck-kaufen-ratgeber/"
    },
    {
      "title": "Stecker, Creolen oder Dangle: Welche Ohrringe passen zu dir?",
      "url": "https://www.preisgucken.com/blog/ohrringe-kaufen-ratgeber/"
    },
    {
      "title": "Die richtige Kettenlänge finden: Choker bis Opernkette erklärt",
      "url": "https://www.preisgucken.com/blog/halsketten-kaufen-ratgeber/"
    }
  ],
  "kleider": [
    {
      "title": "Welches Kleid für welchen Anlass? Cocktailparty bis Gala",
      "url": "https://www.preisgucken.com/blog/abendkleid-cocktailkleid-kaufen-ratgeber/"
    },
    {
      "title": "Alltagskleid, Brautkleid, Umstandskleid: 3 Anlässe, 3 Schnitte",
      "url": "https://www.preisgucken.com/blog/kleider-fuer-jeden-anlass/"
    }
  ],
  "herrenmode": [
    {
      "title": "Painter Pant oder Cargo? Der Workwear-Guide für den Alltag",
      "url": "https://www.preisgucken.com/blog/workwear-trend-painter-pants-chore-jacket/"
    }
  ],
  "schuhe": [
    {
      "title": "Schuhgröße online richtig bestimmen: So vermeidest du Fehlkäufe",
      "url": "https://www.preisgucken.com/blog/schuhe-online-kaufen-groessentabelle/"
    }
  ],
  "damenmode": [
    {
      "title": "Alltagslook für Frauen: Damenmode und Make-up richtig kombinieren",
      "url": "https://www.preisgucken.com/blog/alltagslook-damenmode-make-up-guide/"
    }
  ],
  "kosmetik-beauty": [
    {
      "title": "Alltagslook für Frauen: Damenmode und Make-up richtig kombinieren",
      "url": "https://www.preisgucken.com/blog/alltagslook-damenmode-make-up-guide/"
    },
    {
      "title": "Fruchtpigmente statt Chemie? Was natürliche Kosmetik wirklich bringt",
      "url": "https://www.preisgucken.com/blog/natuerliche-kosmetik-fruchtpigmente/"
    },
    {
      "title": "Muttertag-Geschenke: Ideen nach Budget",
      "url": "https://www.preisgucken.com/blog/muttertag-geschenkideen/"
    }
  ],
  "umstandsmode": [
    {
      "title": "Umstandsmode kaufen: Welche Teile sich wirklich lohnen",
      "url": "https://www.preisgucken.com/blog/umstandsmode-kaufen-guide/"
    }
  ],
  "speicher-laufwerke": [
    {
      "title": "SSD, Festplatte oder USB-Stick kaufen: Welcher Speicher passt?",
      "url": "https://www.preisgucken.com/blog/ssd-festplatte-usb-stick-kaufen-ratgeber/"
    }
  ],
  "pc-komponenten": [
    {
      "title": "PC-Komponenten kaufen: Welche Teile zusammenpassen müssen",
      "url": "https://www.preisgucken.com/blog/pc-komponenten-kaufen-ratgeber/"
    }
  ],
  "kabel-adapter": [
    {
      "title": "Kabel und Adapter kaufen: USB-C, HDMI & Netzwerk richtig wählen",
      "url": "https://www.preisgucken.com/blog/kabel-und-adapter-kaufen-ratgeber/"
    }
  ],
  "elektronik": [
    {
      "title": "Beutellos, Akku oder Roboter? Welcher Staubsauger-Typ zu dir passt",
      "url": "https://www.preisgucken.com/blog/staubsauger-kaufen-ratgeber/"
    }
  ],
  "fernseher": [
    {
      "title": "Fernseher kaufen 2026: OLED, QLED oder LED?",
      "url": "https://www.preisgucken.com/blog/fernseher-kaufen-ratgeber/"
    }
  ],
  "smartphones": [
    {
      "title": "Neues Flaggschiff oder Vorjahresmodell? Wann sich Sparen lohnt",
      "url": "https://www.preisgucken.com/blog/smartphone-kaufen-ratgeber/"
    }
  ],
  "foto-optik": [
    {
      "title": "Carbon oder Aluminium? Das richtige Kamerastativ für deinen Einsatzzweck",
      "url": "https://www.preisgucken.com/blog/kamerastativ-kaufen-ratgeber/"
    }
  ],
  "ueberwachungskameras": [
    {
      "title": "Akku, Solar oder Stromkabel? Der richtige Kameratyp für jeden Einsatzort",
      "url": "https://www.preisgucken.com/blog/ueberwachungskamera-kaufen/"
    },
    {
      "title": "Wildkamera kaufen: Auslöserzeit, Reichweite und Stromversorgung im Check",
      "url": "https://www.preisgucken.com/blog/wildkamera-kaufen-ratgeber/"
    }
  ],
  "pc-it-zubehoer": [
    {
      "title": "Original oder kompatibel? Die wichtigsten Fragen beim PC-Zubehör-Kauf",
      "url": "https://www.preisgucken.com/blog/pc-zubehoer-original-oder-kompatibel/"
    }
  ],
  "heimkino": [
    {
      "title": "Beamer, Leinwand & Sound: So richtest du dein Heimkino richtig ein",
      "url": "https://www.preisgucken.com/blog/heimkino-einrichten-guide/"
    }
  ],
  "monitore": [
    {
      "title": "Monitor oder Beamer? Was für Büro, Gaming und Heimkino wirklich passt",
      "url": "https://www.preisgucken.com/blog/monitor-oder-beamer-kaufratgeber/"
    }
  ],
  "beamer": [
    {
      "title": "Monitor oder Beamer? Was für Büro, Gaming und Heimkino wirklich passt",
      "url": "https://www.preisgucken.com/blog/monitor-oder-beamer-kaufratgeber/"
    }
  ],
  "smart-home-steuerungstechnik": [
    {
      "title": "Smart Home nachrüsten: Schalter, Steckdosen & Steuerung im Vergleich",
      "url": "https://www.preisgucken.com/blog/smart-home-nachruesten-guide/"
    }
  ],
  "wlan-router-mesh": [
    {
      "title": "Mesh-WLAN, Router oder Repeater? Der WLAN-Ausbau-Guide",
      "url": "https://www.preisgucken.com/blog/mesh-wlan-router-repeater-guide/"
    }
  ],
  "kopfhoerer-lautsprecher": [
    {
      "title": "In-Ear, Open-Ear oder Over-Ear? So findest du den richtigen Kopfhörer-Typ",
      "url": "https://www.preisgucken.com/blog/kopfhoerer-typ-in-ear-open-ear-over-ear/"
    },
    {
      "title": "Weihnachtsgeschenke: Ideen nach Budget",
      "url": "https://www.preisgucken.com/blog/weihnachtsgeschenke-ideen-guide/"
    }
  ],
  "handyhuellen": [
    {
      "title": "Handyhülle kaufen: Material, Schutzwirkung und Passform im Überblick",
      "url": "https://www.preisgucken.com/blog/handyhuellen-kaufen-material-schutz/"
    }
  ],
  "heizung": [
    {
      "title": "Elektroheizung kaufen: Heizlüfter, Konvektor oder Ölradiator?",
      "url": "https://www.preisgucken.com/blog/elektroheizung-kaufen-heizluefter-konvektor-oelradiator/"
    }
  ],
  "uhren": [
    {
      "title": "Automatik oder Quarz? Was beim Uhrenkauf wirklich zählt",
      "url": "https://www.preisgucken.com/blog/uhren-kaufen-ratgeber/"
    },
    {
      "title": "Luxusuhren kaufen 2026: Was einen hohen Preis rechtfertigt",
      "url": "https://www.preisgucken.com/blog/luxusuhren-kaufen/"
    }
  ],
  "smartwatch-armbaender": [
    {
      "title": "Passt jedes Ersatzarmband an jede Smartwatch? Kompatibilität erklärt",
      "url": "https://www.preisgucken.com/blog/smartwatch-armband-kaufen-guide/"
    }
  ],
  "gesundheit": [
    {
      "title": "Gesundheitsprodukte online kaufen: Worauf du achten musst",
      "url": "https://www.preisgucken.com/blog/gesundheitsprodukte-online-kaufen/"
    },
    {
      "title": "Rezeptfreie Medikamente online kaufen: OTC & Homöopathie im Preisvergleich",
      "url": "https://www.preisgucken.com/blog/rezeptfreie-medikamente-online-kaufen/"
    }
  ],
  "nahrungsergaenzung-vitamine": [
    {
      "title": "Vitamin D Mangel im Winter: Symptome, Dosierung & Preisvergleich",
      "url": "https://www.preisgucken.com/blog/vitamin-d-mangel-herbst-winter/"
    }
  ],
  "suesswaren": [
    {
      "title": "Pralinen, Tafel oder Geschenkbox? So findest du die richtige Schokolade",
      "url": "https://www.preisgucken.com/blog/schokolade-pralinen-kaufen/"
    },
    {
      "title": "Muttertag-Geschenke: Ideen nach Budget",
      "url": "https://www.preisgucken.com/blog/muttertag-geschenkideen/"
    },
    {
      "title": "Osternest füllen: Geschenkideen für jeden",
      "url": "https://www.preisgucken.com/blog/ostern-geschenkideen-osternest/"
    }
  ],
  "buero-schreibwaren": [
    {
      "title": "Büro-Grundausstattung: Was du wirklich brauchst (und was nicht)",
      "url": "https://www.preisgucken.com/blog/buero-grundausstattung-was-du-wirklich-brauchst/"
    },
    {
      "title": "Schulanfang Checkliste 2026: Was dein Kind wirklich braucht",
      "url": "https://www.preisgucken.com/blog/schulstart-kita-ratgeber/"
    }
  ],
  "balkonkraftwerke": [
    {
      "title": "Mit oder ohne Speicher? So wählst du das richtige Balkonkraftwerk",
      "url": "https://www.preisgucken.com/blog/balkonkraftwerk-kaufen/"
    }
  ],
  "messwerkzeuge": [
    {
      "title": "Messwerkzeuge kaufen: Welches Werkzeug taugt wofür?",
      "url": "https://www.preisgucken.com/blog/messwerkzeuge-kaufen-ratgeber/"
    }
  ],
  "werkzeug-heimwerken": [
    {
      "title": "Werkstatt ausstatten: Was du wirklich brauchst (und was nicht)",
      "url": "https://www.preisgucken.com/blog/werkstatt-ausstattung-was-du-wirklich-brauchst/"
    }
  ],
  "elektroinstallation": [
    {
      "title": "Elektroinstallation kaufen: Schalterprogramm, Dosentyp und Sicherheit im Überblick",
      "url": "https://www.preisgucken.com/blog/elektroinstallation-kaufen/"
    }
  ],
  "arbeitskleidung-arbeitsschutz": [
    {
      "title": "Arbeitskleidung & Arbeitsschutz kaufen: Passform, Norm und Material im Überblick",
      "url": "https://www.preisgucken.com/blog/arbeitskleidung-arbeitsschutz-kaufen/"
    }
  ],
  "beschlaege-schloesser": [
    {
      "title": "Beschläge & Schlösser kaufen: Material, Maße und Belastbarkeit im Überblick",
      "url": "https://www.preisgucken.com/blog/beschlaege-schloesser-kaufen/"
    }
  ],
  "materialbearbeitung": [
    {
      "title": "Fräser, Trenn- und Schleifscheiben kaufen: Material, Norm und Maschinenkompatibilität",
      "url": "https://www.preisgucken.com/blog/materialbearbeitung-fraeser-schleifscheiben-kaufen/"
    }
  ],
  "parfuem": [
    {
      "title": "Parfüm kaufen: EDT, EDP oder Parfum? Der Konzentrations-Guide",
      "url": "https://www.preisgucken.com/blog/parfuem-kaufen-edt-edp-guide/"
    }
  ],
  "gesichtspflege": [
    {
      "title": "Gesichtspflege-Routine: Die 4 Schritte, die wirklich zählen",
      "url": "https://www.preisgucken.com/blog/gesichtspflege-routine-hauttyp-guide/"
    }
  ],
  "tierbedarf": [
    {
      "title": "Hunde- und Katzenbedarf online kaufen: Der Praxis-Guide",
      "url": "https://www.preisgucken.com/blog/haustierbedarf-online-kaufen/"
    }
  ],
  "auto-fahrzeugzubehoer": [
    {
      "title": "Auto-Zubehör kaufen: Von der Dachbox bis zur Anhängerkupplung",
      "url": "https://www.preisgucken.com/blog/auto-zubehoer-kaufratgeber/"
    }
  ],
  "e-scooter": [
    {
      "title": "E-Scooter kaufen: ABE und eKFV erklärt",
      "url": "https://www.preisgucken.com/blog/e-scooter-kaufen-strassenzulassung/"
    }
  ],
  "hoverboards": [
    {
      "title": "Hoverboard kaufen: Zollgröße, Sicherheit & Kart-Umbau erklärt",
      "url": "https://www.preisgucken.com/blog/hoverboard-kaufen-ratgeber/"
    }
  ],
  "taschen-koffer": [
    {
      "title": "Schulanfang Checkliste 2026: Was dein Kind wirklich braucht",
      "url": "https://www.preisgucken.com/blog/schulstart-kita-ratgeber/"
    }
  ],
  "laptops": [
    {
      "title": "Schulanfang Checkliste 2026: Was dein Kind wirklich braucht",
      "url": "https://www.preisgucken.com/blog/schulstart-kita-ratgeber/"
    }
  ],
  "baby-ausstattung": [
    {
      "title": "Schulanfang Checkliste 2026: Was dein Kind wirklich braucht",
      "url": "https://www.preisgucken.com/blog/schulstart-kita-ratgeber/"
    }
  ],
  "spielzeug": [
    {
      "title": "Spielzeug kaufen: Altersfreigabe, Sicherheit und Prüfzeichen im Überblick",
      "url": "https://www.preisgucken.com/blog/spielzeug-kaufen-sicherheit-alter/"
    },
    {
      "title": "Osternest füllen: Geschenkideen für jeden",
      "url": "https://www.preisgucken.com/blog/ostern-geschenkideen-osternest/"
    }
  ],
  "kinderwagen-unterwegs": [
    {
      "title": "Kinderwagen kaufen: Buggy, Kombikinderwagen oder Geschwisterwagen?",
      "url": "https://www.preisgucken.com/blog/kinderwagen-kaufen-typ-guide/"
    }
  ],
  "kinderzimmer": [
    {
      "title": "Babyschlafsack kaufen: Welcher TOG-Wert für welche Jahreszeit?",
      "url": "https://www.preisgucken.com/blog/babyschlafsack-tog-wert-guide/"
    }
  ],
  "motorradzubehoer": [
    {
      "title": "Motorradzubehör kaufen: Passgenauigkeit, Komfort und Optik im Überblick",
      "url": "https://www.preisgucken.com/blog/motorradzubehoer-kaufen/"
    }
  ],
  "mikrowellen": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "toaster": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "standmixer-puerierstaebe": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "kuechenmaschinen": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "fritteusen-heissluftfritteusen": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "kaffeevollautomaten": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "kochplatten-kochfelder": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "eierkocher": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "kleine-kuechengeraete": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "wasserkocher": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    }
  ],
  "kaffeemaschinen": [
    {
      "title": "Küchengeräte im Vergleich: Standmixer, Toaster, Fritteuse & Co. richtig wählen",
      "url": "https://www.preisgucken.com/blog/kuechengeraete-vergleich-kaufratgeber/"
    },
    {
      "title": "Tragbare Espressomaschine kaufen: Der Reise-Guide",
      "url": "https://www.preisgucken.com/blog/tragbare-espressomaschine-kaufen/"
    }
  ],
  "brautkleider": [
    {
      "title": "Hochzeit planen: Brautkleid, Schmuck und Geschenke im Preisvergleich",
      "url": "https://www.preisgucken.com/blog/hochzeitsgeschenke-brautpaar-gaeste/"
    }
  ],
  "sportschuhe": [
    {
      "title": "Fußballschuhe kaufen: FG, SG oder AG? Der Bodenbelag-Guide",
      "url": "https://www.preisgucken.com/blog/fussballschuhe-kaufen-bodenbelag-guide/"
    }
  ],
  "laufbaender": [
    {
      "title": "Walking Pad kaufen: Der Under-Desk-Treadmill-Guide",
      "url": "https://www.preisgucken.com/blog/walking-pad-kaufen-under-desk-treadmill/"
    }
  ]
};
